services:
  prometheus:
    image: prom/prometheus:v2.37.0
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:9.0.0
    container_name: grafana
    environment:
      # Username: admin, Password: admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH="/var/lib/grafana/dashboards/"
    volumes:
      - ./grafana-config/datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
      - ./grafana-config/dashboards.yaml:/etc/grafana/provisioning/dashboards/dashboards.yaml
      - ./grafana-config/dashboard.json:/var/lib/grafana/dashboards/prometheus-stats/dashboard.json
    ports:
      - "3001:3000"

  skynet-app:
    container_name: skynet-app
    build:
      context: ./../../skynet-app
      dockerfile: Dockerfile
    ports:
      - "8000:8000"

