global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'skynet-app'
    static_configs:
      - targets: ['skynet-app:8000']
    metrics_path: '/metrics'
    metric_relabel_configs:
      - source_labels: [__name__]
        regex: (.*)
        target_label: __name__
        replacement: "skynet_$1"

  - job_name: 'lf-app'
    static_configs:
      - targets: ['lf-app-1:8080', 'lf-app-2:8080', 'lf-app-3:8080']

