global:
  scrape_interval: 1m

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'skynet-app'
    static_configs:
      - targets: ['skynet-app:8000']
    metrics_path: '/metrics'