{
 "title": "Demo Service",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "Latency [90th]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum without(instane, status) (rate(demo_api_request_duration_seconds_bucket{job=\"lf-app\"}[5m])))"
    }
   ]
  },
  {
   "title": "Errors [rate-5m]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum without(instance,path) (rate(demo_api_request_duration_seconds_count{status=~\"5..\", job=\"lf-app\"}[5m]))"
    }
   ]
  },
  {
   "title": "Requests [rate-1m]",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 16, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum without(instance, status) (rate(demo_api_request_duration_seconds_count{job=\"lf-app\"}[1m]))",
     "legendFormat": "{{path}}:{{method}}"
    }
   ]
  }
 ]
}