{
 "title": "Web Application Monitoring Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "job", "query": { "query": "label_values(job)" } }
  ]
 },
 "panels": [
  {
   "title": "Requests in Progress",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(skynet_http_requests_in_progress{path!='/metrics', job=\"$job\"})"
    }
   ]
  },
  {
   "title": "Average Request Duration",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(skynet_http_request_duration_seconds_sum{job=\"$job\"}[$__range])) / sum(rate(skynet_http_request_duration_seconds_count{job=\"$job\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Total request",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(skynet_http_request_total{job=\"$job\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Error Rate",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "    ( \r\n      sum(increase(skynet_http_request_total{job=\"$job\", status=~\"4..\"}[$__range])) or vector(0) + \r\n      sum(increase(skynet_http_request_total{job=\"$job\", status=~\"5..\"}[$__range])) or vector(0)\r\n    ) /\r\n       sum(increase(skynet_http_request_total{job=\"$job\"}[$__range])) or vector(0) ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Process Uptime",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - skynet_process_start_time_seconds{job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Requests",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true
  },
  {
   "title": "API Throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "    sum by (normalized_path,method) (\r\n      label_replace(\r\n        rate(skynet_http_request_total{job=\"$job\"}[$__range]),\r\n        \"normalized_path\",\r\n        \"${1}${2}${3}\",\r\n        \"path\",\r\n        \"^(/)(items)?(/)?(.*)?\"\r\n      )\r\n    )",
     "legendFormat": "{{normalized_path}}:{{method}}"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "collapsed": true
  },
  {
   "title": "Requests by Status Code",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(status) (rate(skynet_http_request_total{job=\"$job\"}[$__range]))",
     "legendFormat": "Status: {{status}}"
    }
   ]
  },
  {
   "title": "Duration",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 },
   "collapsed": true
  },
  {
   "title": "API Latency Percentiles",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(skynet_http_request_duration_seconds_bucket{job=\"$job\"}[$__range])))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.75, sum by(le) (rate(skynet_http_request_duration_seconds_bucket{job=\"$job\"}[$__range])))",
     "legendFormat": "p75"
    },
    {
     "expr": "histogram_quantile(0.9, sum by(le) (rate(skynet_http_request_duration_seconds_bucket{job=\"$job\"}[$__range])))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(skynet_http_request_duration_seconds_bucket{job=\"$job\"}[$__range])))",
     "legendFormat": "p95"
    }
   ]
  },
  {
   "title": "Average duration of Requests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(skynet_http_request_duration_seconds_sum{job=\"$job\"}[1m]) / rate(skynet_http_request_duration_seconds_count{job=\"$job\"}[1m])\r\n",
     "legendFormat": "{{method}}:{{path}}:{{status}}"
    }
   ]
  },
  {
   "title": "System Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 },
   "collapsed": true
  },
  {
   "title": "CPU Usage",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "skynet_process_cpu_usage{job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Open File Descriptors",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "skynet_process_open_fds{job=\"$job\"} / skynet_process_max_fds{job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 61 },
   "targets": [
    {
     "expr": "skynet_process_resident_memory_bytes{job=\"$job\"}",
     "legendFormat": "Resident"
    },
    {
     "expr": "skynet_process_virtual_memory_bytes{job=\"$job\"}",
     "legendFormat": "Virtual"
    },
    {
     "expr": "skynet_process_memory_usage_bytes{job=\"$job\"}",
     "legendFormat": "Memory Usage"
    }
   ]
  },
  {
   "title": "GC Generations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 61 },
   "targets": [
    {
     "expr": "rate(skynet_python_gc_objects_collected_total{job=\"$job\"}[$__range])",
     "legendFormat": "Generation: {{generation}}"
    }
   ]
  }
 ]
}